name: Metrics
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 * * * *"}]
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: aleeg0
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
